version: "3"
services:
  timesync_api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_USER="administrator"
      - MYSQL_PASS="password"
      - MYSQL_HOSTNAME="db-instance-id.id.eu-central-1.rds.amazonaws.com"